archivo_de_configuracion:
  'config/ae_config/configuracion_rapida.cfg'
archivo_de_parametros:
  '/parametros.txt'
archivo_de_solucion:
  '/sol.txt'
archivo_de_costos:
  '/costos.txt'
archivo_simplificado:
  '/raw_results.txt'

