production:
  adapter: postgresql
  encoding: unicode
  database: mepaseaste_production
  pool: 5
  username: myapp
  password:

development:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: mepaseaste_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: mepaseaste_test
  pool: 5
  username: root
  password: