production:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: heroku_71a25f26c1d7e46
  pool: 5
  username: b7004484dedd52
  password: 759a6468

development:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: mepaseaste_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: mepaseaste_test
  pool: 5
  username: root
  password: