production:
  adapter: postgresql
  encoding: unicode
  database: delevtfue8i3ks
  pool: 5
  username: dnnnkqxmvvcbxq
  password: _IOQGtVLhCzOOVDgjIqpmIEsAS
  host: ec2-54-225-127-246.compute-1.amazonaws.com

development:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: mepaseaste_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: false
  database: mepaseaste_test
  pool: 5
  username: root
  password: